spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: 110755
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: "very-secret-key-change-me"
  expiration-ms: 3600000
